# Generated by Django 3.0.4 on 2020-05-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('describe', models.CharField(blank=True, default='无', max_length=200, verbose_name='考试说明')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('answer_nums', models.CharField(default=0, editable=False, max_length=10, verbose_name='作答人数')),
                ('release', models.BooleanField(default=False, verbose_name='是否发布')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Specialty', verbose_name='专业')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.TeacherProfile', verbose_name='老师')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('pd', '判断'), ('xz', '选择'), ('tk', '填空'), ('jd', '简答')], max_length=2, verbose_name='题目类型')),
                ('context', models.TextField(verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('choice_a', models.TextField(default='我是答案A', verbose_name='A选项')),
                ('choice_b', models.TextField(default='我是答案B', verbose_name='B选项')),
                ('choice_c', models.TextField(default='我是答案C', verbose_name='C选项')),
                ('choice_d', models.TextField(default='我是答案D', verbose_name='D选项')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Exam', verbose_name='考试名称')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.TeacherProfile', verbose_name='老师')),
            ],
            options={
                'verbose_name': '考试题目',
                'verbose_name_plural': '考试题目',
                'db_table': 'examquestions',
                'ordering': ['question_type'],
            },
        ),
        migrations.CreateModel(
            name='ExamStudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_score', models.FloatField(default=0, verbose_name='判断')),
                ('xz_score', models.FloatField(default=0, verbose_name='选择')),
                ('tk_score', models.FloatField(default=0, verbose_name='填空')),
                ('jd_score', models.FloatField(default=0, verbose_name='简答')),
                ('total', models.FloatField(default=0, verbose_name='总分')),
                ('correct', models.BooleanField(default=False, verbose_name='是否批改')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Exam', verbose_name='考试名称')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.StudentProfile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生考试总分',
                'verbose_name_plural': '学生考试总分',
                'db_table': 'exam_student_score',
                'ordering': ['-total'],
            },
        ),
        migrations.CreateModel(
            name='ExamStudentAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('pd', '判断'), ('xz', '选择'), ('tk', '填空'), ('jd', '简答')], max_length=2, verbose_name='题目类型')),
                ('answer', models.TextField(verbose_name='用户答案')),
                ('score', models.FloatField(default=0, max_length=100, verbose_name='分数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='作答时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Exam', verbose_name='考试名称')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.ExamQuestions', verbose_name='题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.StudentProfile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '做题记录',
                'verbose_name_plural': '做题记录',
                'db_table': 'exam_s_answer_log',
            },
        ),
        migrations.CreateModel(
            name='ExamSocre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_score', models.FloatField(blank=True, default=1, verbose_name='判断分值')),
                ('xz_score', models.FloatField(blank=True, default=1, verbose_name='选择分值')),
                ('tk_score', models.FloatField(blank=True, default=1, verbose_name='填空分值')),
                ('jd_score', models.FloatField(blank=True, default=1, verbose_name='简答分值')),
                ('level', models.CharField(choices=[('2', 'general'), ('3', 'difficult'), ('1', 'easy')], max_length=10, verbose_name='等级')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Exam', verbose_name='考试名称')),
            ],
            options={
                'verbose_name': '考试总分',
                'verbose_name_plural': '考试总分',
                'db_table': 'exam_socre',
                'ordering': ['id'],
            },
        ),
    ]
