# Generated by Django 3.0.4 on 2020-04-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('file', models.FileField(max_length=200, upload_to='upload/courseware/%Y%m%d', verbose_name='公告路径')),
                ('size', models.CharField(editable=False, max_length=20, verbose_name='文件大小')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('download_nums', models.CharField(default=0, editable=False, max_length=10, verbose_name='下载量')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Specialty', verbose_name='专业')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.TeacherProfile', verbose_name='老师')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'coursewares',
                'ordering': ['add_time'],
            },
        ),
    ]
